# Extracted from src/algebra/Makefile.am -- do not edit by hand.
# Bootstrap compilation order for strap stages.
#
# Each strap stage acts as a synchronization barrier: no target in
# stage N+1 may proceed until ALL targets in stage N are complete.
# Cross-stage dependencies are therefore automatically satisfied.
# Only intra-stage ordering matters: within a stage, compilation is
# sequential, so the list order below IS the execution order.
#
# Each strap stage has different dependency semantics.  The --bootstrap
# flag (strap-0) only examines interfaces, categories, and parameter
# types.  The Makefile.am rules for each stage encode exactly the deps
# the compiler needs at that stage.
#
# Constructors referenced as strap-N/XXX in later-stage or post-strap
# rules (but with no strap-N rule of their own) are appended at the
# end of each stage.  Autotools compiles them via pattern rules.

# strap-0: 405 constructors (235 with explicit rules + 170 cross-stage-only)
set(oa_algebra_strap_0
  # -- Single-pass topological order (verified 2026-04-18) --
  TYPE AGG AHYP ATRIG BASTYPE CFCAT COMBOPC DIFFDOM
  DIFFSPC ELEMFUN ELTAB ELTAGG FUNCTOR HYPCAT IEVALAB EVALAB
  KOERCE KONVERT KRCFROM HOMOTOP KVTFROM LOGIC BOOLE ORDTYPE
  PATAB PDDOM PDSPC DSEXT PRIMCAT PTRANFN RADCAT REAL
  RETRACT FRETRCT SEGCAT SEGXCAT SETCAT ABELSG ABELMON ASTCAT
  CABMON CACHSET CTORKIND ES FAMONC FEVALAB FINITE HOAGG
  CLAGG FINAGG IDENT IDPC IFAMON IXAGG LLINSET ABELGRP
  LMODULE LINEXP FLINEXP LNAGG OPERCAT ORDSET BOP FLAGG
  KERNEL OASGP OAMON OCAMON OAGROUP OAMONS INDE ORDFIN
  CHAR OUTFORM OVERSET PATMAB FPATMAB PATRES PATTERN PROPLOG
  BOOLEAN RCAGG REPDB REPSQ RLINSET LINSET RMODULE BMODULE
  RNGBIND SASTCAT SEG SEGBIND SETAGG SEXCAT INFORM SEXOF
  SGROUP MONOID GROUP RNG SMAGG A1AGG ARR2CAT BGAGG
  DIOPS DIAGG ELAGG FLASORT FSAGG CCLASS KDAGG MDAGG
  MSETAGG MSET SPACEC SPFCAT SRAGG SRING DIOID RING
  CHARNZ CHARZ COMRING DIFRING ENTIRER MODULE ALGEBRA DIVRING
  INTDOM GCDDOM LO ORDRING OINTDOM OREPCAT LODOCAT LODO
  PDRING DIFEXT PID EUCDOM SPACE3 STEP STRING SYMBOL
  TBAGG INTABL TABLE TRIGCAT TRANFUN INTCAT LFCAT UFD
  FIELD ACF AMR AN FAMR FPC FFIELDC FS
  ACFS EXPR INS COMBINAT FR INT INTFACT MATCAT
  MATRIX NNI PFECAT PI PMINS POLYCAT GENPGCD PFBR
  PR PRIMES PSCAT QFCAT FRAC RNS FPS DFLOAT
  FLOAT INTRVL SEX SINT UNISEG UPOLYC DDFACT FINRALG
  FRAMALG MONOGEN COMPCAT COMPLEX SAE SUP UPSCAT FS2UPS
  ULSCAT ULSCCAT ULS UPXSCAT UPXSCCA EFUPXS UPXS URAGG
  STAGG LSAGG ALAGG ALIST LIST LZSTAGG STREAM UTSCAT
  EFULS UTYPE MAYBE SPADXPT SPADAST SYNTAX VECTCAT PTCAT
  POINT VECTOR VSPACE DIRPCAT EQ GDMP DMP HDP
  XF FAXF NORMRETR
  # -- Cross-stage-only: referenced from strap-1/2 but no strap-0 rule --
  ADDAST ALGFACT ANY ANY1 APPRULE ARITY ATTRAST BOP1
  BRILL CAPSLAST CARD CASEAST CATAST CINTSLPE CLLCTAST COLONAST
  COMMAAST COMMONOP COMMUPC COMPFACT COMPLPAT CPIMA CPMATCH CRCEAST
  CSTTOOLS CYCLOTOM DBASIS DEFAST DFSFUN DIRPROD DLP EFSTRUC
  EMR ES2 EXITAST EXPEXPAN EXPR2 FACTFUNC FACUTIL FFPOLY
  FFSLPE FLAGG2 FR2 FRUTIL FS2 FS2EXPXP FSCINT FSINT
  GALFACT GB GENEEZ GENMFACT GENUFACT GHENSEL GRDEF HASAST
  HASHTBL HEADAST HEUGCD IDPT IFAST IMATLIN IMATQF IMPTAST
  INAST INFORM1 INFSP INNMFACT INPSIGN INTEF INTRET INTSLPE
  INTTOOLS IR IR2 IR2F IRFORM IROOT ISAST ITRIGMNP
  JOINAST LEADCDET LETAST LIMITPS LIST2MAP LODEEF LPEFRAC LSTAST
  MACROAST MAPPAST MATLIN MATSTOR MCDEN MDDFACT MFINFACT MKFUNC
  MKUCFUNC MLIFT MODRING MPC2 MPC3 MPCPF MPRFF MRATFAC
  MULTFACT MULTSQFR NODE1 NONE NTPOLFN NUMFMT ODESYS ONECOMP
  ORDCOMP OUT PARAMAST PATTERN1 PDECOMP PFBRU PGCD PMASSFS
  PMDOWN PMPLCAT PMQFCAT PMSYM PMTOOLS POLY POLYCATQ POLYLIFT
  PRIMARR PRS PRTDAST PSQFR QQUTAST RATFACT REF RETAST
  RPTAST RSTRCAST SAEFACT SAERFFC SEGAST SEQAST SIG SIGAST
  SIGNEF SIGNRF STEPAST STREAM2 STTAYLOR SUCHTAST TOOLSIGN TRIGMNIP
  TRMANIP TWOFACT TYPEAST UDPO ULSCONS UP UPDECOMP UPDIVP
  UPMP UPOLYC2 UPSQFREE UTS VARIABLE VIEW VOID WHEREAST
  WHILEAST YSTREAM
)

# strap-1: 380 constructors (303 with topo order + 77 cross-stage-only)
set(oa_algebra_strap_1
  # -- Topological order (verified 2026-04-18, 303 constructors) --
  # Pass-1 constructors first (300), then pass-2 transients (FS SYMBOL LIST)
  # at the end so they find all accumulated strap-1 FASLs.
  ACF ACFS ASTCAT CATAST DEFAST DFSFUN EMR EXPR2
  FR2 GENMFACT GENUFACT INMODGCD HEUGCD ITAYLOR ITFORM MKUCFUNC
  MONOGEN MPRFF MULTFACT PMPLCAT PMQFCAT POLYROOT PTPACK RADCAT
  RULE SIGNRF SPADAST SPADXPT TRIGMNIP TYPE AGG AHYP
  ALAGG ALIST BASTYPE CACHSET CFCAT COLOR DIFFDOM DIFFSPC
  DIRPCAT ELTAB ELTAGG FACUTIL FAMONC FAGROUP FLAGG2 FUNCTOR
  GBINTERN IDENT IFARRAY FARRAY KOERCE KONVERT KRCFROM KVTFROM
  LIST2 LOGIC BOOLE MATCAT2 COMPCAT COMPLEX MATLIN MCDEN
  MDAGG LMDICT INTFACT NONE NONE1 ANY1 NPCOEF ORDTYPE
  OVAR GDMP HDMP LGROBP LINBASIS PALETTE DROPT DROPT1
  DROPT0 PATAB PATRES2 CPMATCH PDDOM PDSPC DSEXT PDRING
  PMDOWN POLTOPOL GROEBSOL POLY2 CMPLXRT PPCURVE PLOT CLIP
  PLOTTOOL PRIMCAT LFCAT PUSHVAR MPCPF REAL REF RETRACT
  FRETRCT SCACHE KERNEL SEGCAT SEGXCAT SET SETCAT ABELSG
  ABELMON ARITY BOP1 CABMON FINITE IDPC IEVALAB EVALAB
  FEVALAB HOAGG CLAGG FINAGG IXAGG LLINSET LNAGG FLAGG
  OPERCAT CTORCAT CTORCALL ORDSET BOP OASGP OAMON OCAMON
  OAMONS ORDFIN OUTFORM PAIR HEADAST IDPO IDPAM IDPOAM
  IDPOAMS IDPT IMPTAST INDE PATMAB FPATMAB PATRES PATTERN
  PROPLOG BOOLEAN RCAGG RLINSET LINSET SAOS INNMFACT MULTSQFR
  PFBR PGCD SEG SETAGG SEXCAT SGROUP MONOID ELEMFUN
  GROUP SMAGG A1AGG ARR2CAT BGAGG BTAGG DIOPS DIAGG
  ELAGG IARRAY1 ARRAY1 IBITS KDAGG FSAGG CCLASS CHAR
  PRIMARR ES INFORM SMP COMBF LF LIMITPS MFINFACT
  ODEINT ODEEF POLY SIGNEF SRAGG SRING DIOID STEP
  STREAM3 STRING STTAYLOR SUP2 MLIFT POLYCATQ ALGMANIP
  FSINT IAN AN TBAGG TABLE ULS UNISEG
  UP UPDECOMP URAGG STAGG LSAGG LZSTAGG STREAM
  UTS UTYPE MAYBE ABELGRP CTOR CATCTOR IDPAG FM
  LMODULE LINEXP FLINEXP OAGROUP RMODULE BMODULE RNG RING
  ATRIG CHARNZ CHARZ COMRING DIFRING DIFEXT ENTIRER GALUTIL
  HYPCAT MODULE ALGEBRA DIVRING INTDOM FR GCDDOM LA
  ORDRING OINTDOM PID EUCDOM TRIGCAT TRANFUN UFD FIELD
  AMR FAMR FPC FFIELDC INS MATCAT PFECAT PR
  QFCAT FRAC RNS FPS DFLOAT VECTCAT VECTOR POLYCAT
  UPOLYC GALFACTU GALPOLYU GALFACT MODMON DDFACT SUP INT
  FLOAT IARRAY2 MATRIX NNI PI SINT VECTOR2 GENEEZ
  VSPACE EQ XF FAXF FFP FFX TWOFACT
  # -- Pass-2 transients: need all 300 pass-1 FASLs available --
  FS SYMBOL LIST
  # -- Cross-stage-only: referenced from strap-2 but no strap-1 rule --
  AF ANY BRILL CARD CINTSLPE COMBINAT COMBOPC COMMONOP
  COMMUPC COMPLPAT COORDSYS CPIMA CTORKIND CYCLOTOM DIRPROD DLP
  DMP EF ES2 FFSLPE FINRALG FLASORT FRAMALG FRUTIL
  FS2 FSPECF GENPGCD GHENSEL INTHEORY INTRET INTSLPE IROOT
  KERNEL2 LIST2MAP LPEFRAC MATSTOR MDDFACT MRATFAC MSET MSETAGG
  NUMFMT ONECOMP ORDCOMP PATTERN1 PFBRU PMINS PMSYM PMTOOLS
  POINT POLYLIFT PRIMES PRS PSCAT PSQFR PTCAT REAL0
  REPDB REPSQ SEGBIND SEX SIG SPFCAT STTF STTFNC
  SUBRESP SUPFRACF SYNTAX TOOLSIGN ULSCCAT UPMP UPOLYC2 UPSCAT
  UPSQFREE UPXSCONS VARIABLE VIEWDEF VOID
)

# strap-2: 293 constructors (257 topo order + 36 cross-stage-only)
set(oa_algebra_strap_2
  # -- Single-pass topological order (verified 2026-04-18, 257 constructors) --
  APPRULE ARRAY1 BTAGG DFSFUN FR2 GALFACT GENEEZ GENMFACT
  GRIMAGE IBITS IEVALAB EVALAB INFSP KERNEL LINELT LLINSET
  MONOGEN COMPCAT COMPLEX MPRFF MULTFACT MULTSQFR NODE1 PATRES
  PFBR PLOT PMPLCAT PNTHEORY NTPOLFN RADCAT TYPE AGG
  AHYP BASTYPE CFCAT DIFFDOM DIFFSPC ELEMFUN ELTAB ELTAGG
  FUNCTOR FEVALAB HASHTBL HOMOTOP INTABL INTCAT INTRVL IRFORM
  KOERCE KONVERT KRCFROM KVTFROM LOGIC BOOLE OPSIG CATEGORY
  ORDTYPE PATAB PDDOM PDECOMP ACF ACFS PDSPC DSEXT
  PDRING PMKERNEL PMFS EXPR EXPR2 PSCAT REAL RETRACT
  FRETRCT SASTCAT ADDAST ATTRAST CAPSLAST CASEAST CATAST CLLCTAST
  COMMAAST DEFAST EXITAST HASAST IFAST INAST ISAST LETAST
  LSTAST MACROAST QQUTAST RETAST RPTAST SEGAST SEGCAT SEGXCAT
  SEQAST SETCAT ABELSG ABELMON CABMON ABELGRP CACHSET FINITE
  HOAGG CLAGG FINAGG IDPC IDPO IDPAM IDPAG FM
  IXAGG LMODULE LINEXP FLINEXP LNAGG FLAGG NONE ORDSET
  OASGP OAMON OCAMON OAGROUP OAMONS ORDFIN OUTFORM PAIR
  PATMAB FPATMAB PATTERN PROPLOG BOOLEAN RCAGG REF RLINSET
  LINSET RMODULE BMODULE SETAGG SEXCAT SEXOF SEX ANY
  SGROUP MONOID GROUP RNG SIGAST SIGNEF SMAGG A1AGG
  ARR2CAT BGAGG DIOPS DIAGG ELAGG KDAGG FSAGG CCLASS
  CHAR MATCAT PRIMARR IARRAY1 IARRAY2 MATRIX SPADXPT SRAGG
  SRING DIOID RING ATRIG CHARNZ CHARZ COMRING DIFRING
  DIFEXT ENTIRER ES HYPCAT MODULE ALGEBRA INTDOM GCDDOM
  ORDRING OINTDOM STEP STEPAST STRING SUCHTAST TBAGG TABLE
  TOOLSIGN TRIGCAT TRANFUN TYPEAST COLONAST CRCEAST IMPTAST JOINAST
  MAPPAST PRTDAST RSTRCAST UDPO POLY ULSCAT UNISEG UPSCAT
  UPXSCAT UPXSCCA UPXS URAGG STAGG LSAGG ALAGG ALIST
  LIST UTSCAT UTS UTYPE MAYBE PID EUCDOM VECTCAT
  VECTOR VOID FR SYMBOL INFORM UFD INS PFECAT
  QFCAT FRAC DIVRING FIELD AMR FAMR FPC FFIELDC
  POLYCAT PR RNS FPS DFLOAT UPOLYC SUP INT
  FLOAT NNI PI SINT VSPACE EQ WHEREAST WHILEAST
  SPADAST
  # -- Cross-stage-only: referenced from post-strap but no strap-2 rule --
  AN ARITY BOP BOP1 COMBINAT COMMONOP CSTTOOLS DBASIS
  FLASORT FRUTIL GENPGCD HEUGCD IDENT INDE INTFACT INTSLPE
  LPEFRAC LSMP MATCAT2 MCDEN NUMFMT PGCD PMINS PMQFCAT
  PMSYM POLYLIFT PRIMES PSQFR REPDB REPSQ STREAM2 STREAM3
  SUP2 UPOLYC2 UPSQFREE VECTOR2
)

