# Extracted from src/algebra/Makefile.am -- do not edit by hand.
# Bootstrap compilation order for strap stages.

# strap-0: 203 constructors
set(oa_algebra_strap_0
  TYPE UTYPE FUNCTOR BASTYPE KOERCE KONVERT RETRACT FRETRCT
  SETCAT FINITE ORDTYPE ORDSET ORDFIN LOGIC BOOLE PROPLOG
  SEXCAT LLINSET RLINSET LINSET ABELSG ABELMON CABMON OCAMON
  SGROUP OAMON OASGP MONOID GROUP ABELGRP OAGROUP RNG
  LMODULE RMODULE SRING ORDRING RING DIOID COMRING INTDOM
  GCDDOM BMODULE MODULE ENTIRER ALGEBRA EUCDOM PID OINTDOM
  FIELD DIVRING DIFFSPC DIFFDOM DIFRING LINEXP CFCAT REAL
  CHARZ STEP PATMAB UFD PDSPC DSEXT DIFEXT PFECAT
  QFCAT FPATMAB PATAB FLINEXP FEVALAB CHARNZ INS FPS
  RNS TRANFUN TRIGCAT ATRIG HYPCAT AHYP ELEMFUN SEGCAT
  SEGXCAT VECTCAT ARR2CAT MATCAT IDPC AMR FAMR POLYCAT
  PDRING UPOLYC TBAGG KDAGG DIAGG DIOPS BGAGG SMAGG
  LSAGG STAGG URAGG RCAGG ELAGG SRAGG A1AGG FLAGG
  FINAGG LNAGG CLAGG IXAGG HOAGG SETAGG AGG ELTAGG
  ELTAB EVALAB IEVALAB BOOLEAN SINT INT NNI OAMONS
  PI STRING LIST VECTOR OUTFORM INFORM OVERSET CTORKIND
  MAYBE DFLOAT FLOAT FRAC MATRIX SUP PR TABLE
  EQ ES VSPACE UNISEG SYNTAX FR PATTERN SEX
  SEXOF SYMBOL BOP ALAGG ALIST CHAR KERNEL REPSQ
  REPDB OPERCAT CACHSET LO CCLASS FSAGG FLASORT GENPGCD
  PFBR DDFACT FFIELDC INDE STREAM SAE MONOGEN FRAMALG
  FINRALG NORMRETR FAXF COMPLEX COMPCAT MSET MSETAGG AN
  SEGBIND EXPR ACFS IFAMON HDP DMP LFCAT INTRVL
  FS2UPS UPSCAT UPXS EFUPXS ULS EFULS POINT SPACE3
  LODO LODOCAT SASTCAT ASTCAT SPADAST SPADXPT INTFACT PRIMES
  COMBINAT PATRES PMINS
)

# strap-1: 257 constructors
set(oa_algebra_strap_1
  FUNCTOR BASTYPE SETCAT LOGIC BOOLE PROPLOG ORDTYPE ORDSET
  FINITE ORDFIN PID GCDDOM EUCDOM UFD LLINSET RLINSET
  LINSET SGROUP ABELSG MONOID ABELMON CABMON OCAMON OAMON
  OASGP OAMONS ABELGRP OAGROUP RNG LMODULE RMODULE BMODULE
  SRING GROUP RING DIOID ORDRING CHARZ COMRING ALGEBRA
  MODULE INTDOM ENTIRER OINTDOM FIELD FPC CHARNZ FFIELDC
  STEP DIVRING REAL INS PATMAB PATTERN LINEXP FPS
  RNS DSEXT DIFEXT DIFRING DIFFSPC PDRING PDSPC PDDOM
  TRANFUN TRIGCAT ATRIG HYPCAT AHYP ELEMFUN IDPC AMR
  FAMR FRETRCT POLYCAT UPOLYC PFECAT QFCAT FEVALAB FPATMAB
  PATAB FLINEXP OPERCAT ARR2CAT SMAGG BTAGG FSAGG KDAGG
  DIAGG DIOPS BGAGG LSAGG STAGG URAGG RCAGG ELAGG
  SRAGG A1AGG FLAGG FINAGG LNAGG CLAGG IXAGG HOAGG
  SETAGG AGG ELTAGG ELTAB EVALAB IEVALAB SEXCAT CTORCAT
  VSPACE MATCAT VECTCAT RADCAT ARITY CTORCALL OUTFORM BOOLEAN
  SINT PI NNI INT MAYBE DFLOAT DFSFUN FLOAT
  SUP PR FM IDPAG IDPAM IDPT IDPO PAIR
  MATRIX IARRAY2 PRIMARR LIST VECTOR ARRAY1 IARRAY1 FRAC
  STRING CHAR CCLASS TABLE IBITS CTOR CATCTOR SAOS
  STREAM LZSTAGG BOP ES EQ LA FR INFORM
  SEGXCAT SYMBOL INTFACT LMDICT SET FARRAY UNISEG SEG
  PATRES MCDEN LIST2 PMQFCAT PFBR MULTSQFR PMPLCAT DDFACT
  MODMON TWOFACT FFX FFP FAXF MATLIN GALFACT GALFACTU
  GALUTIL GALPOLYU HEUGCD INMODGCD ANY1 POLY MULTFACT INDE
  IDPOAMS GENEEZ MLIFT VECTOR2 PMDOWN BOP1 KERNEL UPDECOMP
  COMPLEX COMPCAT MONOGEN ALIST MPRFF INNMFACT GENUFACT EMR
  MFINFACT ACF FS LF LFCAT ALGMANIP POLYROOT AN
  IAN EXPR2 MKUCFUNC FAGROUP CMPLXRT POLTOPOL HDMP GDMP
  GROEBSOL GENMFACT COMBF ACFS MPCPF SIGNEF SIGNRF LIMITPS
  TRIGMNIP ULS UTS ITAYLOR STTAYLOR FSINT UP RULE
  PTPACK PLOTTOOL CPMATCH DROPT0 DROPT1 DROPT ODEEF ASTCAT
  IMPTAST DEFAST CATAST HEADAST ITFORM LINBASIS FR2 SPADXPT
  SPADAST
)

# strap-2: 208 constructors
set(oa_algebra_strap_2
  FUNCTOR KOERCE KONVERT RETRACT BASTYPE FRETRCT SETCAT FINITE
  ORDTYPE ORDSET ORDFIN LOGIC BOOLE PROPLOG LLINSET RLINSET
  LINSET SGROUP ABELSG MONOID ABELMON CABMON OCAMON OAMON
  OASGP ABELGRP OAGROUP RNG LMODULE RMODULE BMODULE SRING
  RING DIOID ORDRING COMRING MODULE INTDOM GCDDOM ENTIRER
  OINTDOM ALGEBRA EUCDOM PID DIVRING FIELD DIFFDOM DIFFSPC
  DIFRING DSEXT PDDOM PDSPC PDRING DIFEXT LINEXP CFCAT
  REAL CHARZ STEP PATMAB PATRES UFD INS FPS
  RNS RADCAT PFECAT QFCAT FEVALAB CHARNZ FPATMAB PATAB
  FLINEXP TRANFUN TRIGCAT ATRIG HYPCAT AHYP ELEMFUN IDPC
  AMR FAMR POLYCAT UPOLYC ARR2CAT FSAGG ALAGG LSAGG
  TBAGG KDAGG DIAGG DIOPS SMAGG BGAGG STAGG URAGG
  RCAGG ELAGG SRAGG A1AGG FLAGG FINAGG LNAGG CLAGG
  IXAGG HOAGG SETAGG AGG ELTAGG ELTAB EVALAB IEVALAB
  SEXCAT MATCAT CATEGORY SINT PI NNI OAMONS INT
  DFLOAT FLOAT SUP FFIELDC FPC PR FM IDPAG
  IDPAM IDPO VECTOR ARRAY1 VECTCAT IARRAY1 PRIMARR PAIR
  MATRIX IARRAY2 INFORM LIST SEX OUTFORM SEXOF ANY
  NONE SYMBOL ALIST REF STRING FRAC CHAR CCLASS
  TABLE IBITS MAYBE BOOLEAN EQ VSPACE GROUP ES
  CACHSET BTAGG UNISEG PATTERN FR KERNEL PFBR MULTSQFR
  PMPLCAT GALFACT DFSFUN POLY MULTFACT MONOGEN COMPCAT GENEEZ
  MPRFF ACFS ACF NTPOLFN PNTHEORY EXPR EXPR2 PMFS
  INFSP GENMFACT TOOLSIGN SIGNEF INTRVL UPXS UPXSCCA UPXSCAT
  UPSCAT UTS UTSCAT APPRULE PLOT GRIMAGE NODE1 SPADAST
  DEFAST SASTCAT CATAST TYPEAST IRFORM LINELT FR2 COMPLEX
)

