name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: ${{ matrix.os }} -x- ${{ matrix.cxx }} -x- ${{ matrix.lisp }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04 ]
        cxx: [ g++-14 ]
        lisp: [ sbcl ]

    steps:
      - uses: actions/checkout@v2

      - name: Install Lisp and C++ compilers
        run: |
          sudo apt-get update && sudo apt upgrade -y
          sudo apt-get install build-essential ${{ matrix.cxx }} ${{ matrix.lisp }} libxt-dev libxpm-dev texlive
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100 --slave /usr/bin/g++ g++ /usr/bin/g++-14 --slave /usr/bin/gcov gcov /usr/bin/gcov-14

      - name: Configure & Build & Test
        run: |
          mkdir ${{ matrix.lisp }}-build && cd ${{ matrix.lisp }}-build
          touch ../configure && sleep 1
          ../configure --disable-maintainer-mode --with-lisp=${{ matrix.lisp }}
          time make
          time make check

